# Generated by Django 3.2.14 on 2022-10-07 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='지원자명', max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='지원자 이메일', max_length=64)),
                ('skill', models.CharField(help_text='사용 기술', max_length=32)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='회사명', max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='회사 이메일', max_length=64)),
                ('nation', models.CharField(help_text='국가', max_length=32)),
                ('region', models.CharField(help_text='지역', max_length=64)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='채용 제목', max_length=64)),
                ('content', models.TextField()),
                ('skill', models.CharField(help_text='사용 기술', max_length=32)),
                ('recruit_compensation', models.IntegerField(help_text='채용 보상금')),
                ('recruit_position', models.CharField(help_text='채용 포지션', max_length=32)),
            ],
            options={
                'db_table': 'job_posting',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.applicant')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.jobposting')),
            ],
            options={
                'db_table': 'application_details',
            },
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_cmpy_name_email'),
        ),
        migrations.AddConstraint(
            model_name='applicationdetails',
            constraint=models.UniqueConstraint(fields=('job_posting', 'applicant'), name='unique_applicant_details_job_posting_applicant'),
        ),
    ]
