# Generated by Django 3.2.14 on 2022-10-16 09:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import recruit.models


class Migration(migrations.Migration):

    replaces = [('recruit', '0003_auto_20221016_1648'), ('recruit', '0004_auto_20221016_1723'), ('recruit', '0005_applicant_company'), ('recruit', '0006_alter_jobposting_company')]

    dependencies = [
        ('recruit', '0002_auto_20221007_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationDetails',
            new_name='ApplicationHistory',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(countries=recruit.models.G8Countries, max_length=2),
        ),
        migrations.AlterModelTable(
            name='applicationhistory',
            table='application_history',
        ),
        migrations.RemoveConstraint(
            model_name='applicant',
            name='unique_cmpy_name_email',
        ),
        migrations.RemoveConstraint(
            model_name='applicationhistory',
            name='unique_applicant_details_job_posting_applicant',
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_applicant_name_email'),
        ),
        migrations.AddConstraint(
            model_name='applicationhistory',
            constraint=models.UniqueConstraint(fields=('job_posting', 'applicant'), name='unique_applicant_history_job_posting_applicant'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_cmpy_name_email'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='recruit.company'),
        ),
    ]
