# Generated by Django 3.2.14 on 2022-10-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20221016_1648_squashed_0006_alter_jobposting_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='company',
        ),
    ]
